name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Warnings Test -- 3pts
      id: warnings-test-3pts
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Warnings Test -- 3pts
        setup-command: cmake -B Builds; make -C Builds > compile_output.txt 2>&1;
          cat compile_output.txt
        command: if grep -i 'warning' compile_output.txt; then echo 'Compiler warnings
          found.'; exit 1; else echo 'No compiler warnings.'; exit 0; fi
        timeout: 1
        max-score: 3
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        WARNINGS-TEST-3PTS_RESULTS: "${{steps.warnings-test-3pts.outputs.result}}"
      with:
        runners: warnings-test-3pts
